### ISSUE TITLE
CLIP Module??

### ISSUE THREAD

**Issue by JHNewton** [tusharbhutt/Endless-Nodes#4]
OK, I used manager in Comfyui to install your package.  I'm getting an error saying that ther is no CLIP module.  I ran pip to install the requirements.txt file.  Here is the results:

PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes> D:\ComfyUI_windows_portable\python_embeded\python.exe -s -m pip install -r requirements.txt
Collecting clip (from -r requirements.txt (line 1))
  Using cached clip-0.2.0.tar.gz (5.5 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\John\AppData\Local\Temp\pip-install-t97mvhaf\clip_583d4ae394354b519e59d31aa84bd99a\setup.py", line 4, in <module>
          import clip
      ModuleNotFoundError: No module named 'clip'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
PS D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Endless-Nodes>

Not sure what the problems is as I'm not a python programmer.  In fact, I haven't done any sort of programming in close to 20 years so any assistance would be greatly appreciated.

**Comment by tusharbhutt** [comment]
I had that issue too when trying to install CLIP for other nodes, so I went to the source.  They have these install instructions:  

https://github.com/openai/CLIP#usage

If you are on a Windows machine (and it seems that you are), navigate to the folder with ComfyUI in it, right-click and open a command prompt.  Then type:

```
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git
```

Let me know if that worked for you.  I seem to remember I had to jump through a lot of hoops to get it installed.

**Comment by JHNewton** [comment]
Thanks, gott the nodes to load.

For a folder I want to use G:\output\[time(%Y-%m-%d)].  Only thing is, that
there is nothing there, not even a folder. From the error msg in the
console, it does not seem to be creating the folder/directory. Shouldn't it
be creating the directory if it dosen't exist?


Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by tusharbhutt** [comment]
Yes... it should.  But are you actaulyl using

 **G:\output\[time(%Y-%m-%d)].** 
 
 Or:
 
  **G:\output\(%Y-%m-%d)**
  
  ?
  
  The former is specific to the WAS nodes, I think.

**Comment by JHNewton** [comment]
I'm using the first one.  This is the same as WAS uses.  Now, I seem to
recall that WAS's node had problems creating directories on drives other
than the default drive.  I was hoping that you had overcome that issue.  I
really like the concept of creating both an image and a meta data file and
being able to save them on any drive on your system.

I'm almost intrigued enough to take a peek inside python, but I'm not quite
sure I want to try and tackle a new language 75. I think I'd rather spend
my time as a user of this really cool tool and create images.

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by tusharbhutt** [comment]
My code does save the image and json to two separate folders on different drives, but for the custom date codes, you have to use the python standard as noted in the readme (duplicated here for you: https://docs.python.org/2/library/time.html#time.sleep)

When using the Python standard were you still not able to save to a different drive/folder?  I ask because I'm literally doing that right now as I type this.

**Comment by JHNewton** [comment]
OK, here is a screen shot of how I have the node setup.  [image:
806e9618-43d5-4703-afae-bf12b2e88f18.jpg]

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by JHNewton** [comment]
Here is what I'm seeing my the console:
WAS Node Suite: Image file saved to:
D:\ComfyUI_windows_portable\ComfyUI\output\2023-10-07\JHN_2023-10-07_0038.png
 + Unable to save file: {'[time(%Y-%m-%d)]\\JHN_[time(%Y-%m-%d)]_0001.png'}
[Errno 2] No such file or directory:
'[time(%Y-%m-%d)]\\JHN_[time(%Y-%m-%d)]_0001.png'

And here is the setup:
[image: image.png]

For my purposes I'd like for only the prompts to be saved to the jason file
as the full workflow should be saved in the image like what WAS has.
Does that make sense?

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by tusharbhutt** [comment]
> Here is what I'm seeing my the console: 
>WAS Node Suite: Image file saved to: D:\ComfyUI_windows_portable\ComfyUI\output\2023-10-07\JHN_2023-10-07_0038.png 
>+ Unable to save file: {'[time(%Y-%m-%d)]\\JHN_[time(%Y-%m-%d)]_0001.png'} 
>[Errno 2] No such file or directory: '[time(%Y-%m-%d)]\\JHN_[time(%Y-%m-%d)]_0001.png' 
>
>And here is the setup: [image: image.png] 

There is no image file attached... and again, my node **_does not_** use [time(%Y-%m-%d)] as part of the name, it's just %Y-%m-%d, no square brackets, no "time".

**Comment by trashie65** [comment]
Updated pack can see more errors, still dont load... i think i will leave it at that, not bother to use... thank you

**Comment by JHNewton** [comment]
Not a problem.  You have a very good idea.  Not being familiar with python,
I gather that there is more than one way to display the date/time meta
data. Oh well, guess I'll poke my nose into the python book I purchased and
see if I really want to take up programming once again. Thanks for taking a
look. Keep up the good fight.

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by tusharbhutt** [comment]
Does your date and time input look like the top line in the image below?

![imagesaverone](https://github.com/tusharbhutt/Endless-Nodes/assets/26264462/0479a71f-4890-40ec-84e3-4c4a1bd81214)

**Comment by JHNewton** [comment]
I've been using the example from the WAS save image node.  Very similar but
with square brackets and "time". JHN_[time(%y-%m-%d)]  While it has been a
very long time since I've done any programming, and none whatsoever in
python, I can still gleam a piece or two of information from poking around
in  code.  I noticed that WAS is calling a different time module than you
are.  I suspect this is why when I try to use his syntax I get negative
results. Just an observation, nothing more.

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle
